import { readFile, mkdir, writeFile } from 'node:fs/promises';

// Resolve from this script so the command also works outside the project root.
const inputUrl = new URL('../design/montage.tokens.json', import.meta.url);
const outputUrl = new URL('../src/tokens.css', import.meta.url);

const kebab = (name) => String(name)
  .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
  .replaceAll('.', '-')
  .toLowerCase();

function add(map, name, value, usage = '') {
  const variable = `--${kebab(name)}`;
  if (!/^--[a-z0-9-]+$/.test(variable)) {
    throw new Error(`Invalid CSS variable name: ${name}`);
  }
  if (map.has(variable)) {
    throw new Error(`CSS variable name collision: ${variable}`);
  }
  if (!['string', 'number'].includes(typeof value) || /[;{}\r\n]/.test(String(value))) {
    throw new Error(`Invalid CSS value for ${variable}`);
  }
  map.set(variable, { value: String(value), usage });
}

function addGroup(map, group, prefix = '') {
  if (!group || typeof group !== 'object') {
    throw new Error(`Missing token group: ${prefix}`);
  }
  for (const [key, token] of Object.entries(group)) {
    add(map, prefix ? `${prefix}.${key}` : key, token.value, token.usage);
  }
}

function addPlatform(map, group) {
  // Platform tokens contain CSS declaration lists; expose each property separately.
  for (const [key, token] of Object.entries(group)) {
    for (const declaration of token.value.split(';').map((s) => s.trim()).filter(Boolean)) {
      const match = declaration.match(/^([a-z-]+)\s*:\s*(.+)$/s);
      if (!match) throw new Error(`Invalid platform declaration: ${key}`);
      add(map, `${key}.${match[1]}`, match[2], token.usage);
    }
  }
}

function renderBlock(selector, map) {
  const lines = [...map].flatMap(([name, { value, usage }]) => {
    const safeUsage = String(usage).replaceAll('*/', '* /').replace(/[\r\n]+/g, ' ');
    return [safeUsage ? `  /* ${safeUsage} */` : null, `  ${name}: ${value};`].filter(Boolean);
  });
  return `${selector} {\n${lines.join('\n')}\n}`;
}

async function main() {
  const tokens = JSON.parse(await readFile(inputUrl, 'utf8'));
  const common = new Map();
  const light = new Map();
  const dark = new Map();
  const classes = [];

  addGroup(common, tokens.colors.atomic);
  addGroup(common, tokens.spacing, 'space');
  addGroup(common, tokens.radius, 'radius');
  addGroup(common, tokens.opacity, 'opacity');
  addGroup(common, tokens.breakpoint, 'breakpoint');
  addGroup(common, tokens.zIndex, 'z-index');

  for (const [mode, map] of [['light', light], ['dark', dark]]) {
    addGroup(map, tokens.colors[mode]);
    addGroup(map, tokens.shadows[mode]);
    addPlatform(map, tokens.platformStyles[mode]);
  }
  if ([...light.keys()].sort().join('\n') !== [...dark.keys()].sort().join('\n')) {
    throw new Error('Light and dark token names must match.');
  }

  const classNames = new Set();
  for (const [variant, token] of Object.entries(tokens.typography)) {
    const className = kebab(variant);
    if (classNames.has(className)) throw new Error(`Typography class collision: ${className}`);
    classNames.add(className);
    const prefix = `type.${variant}`;
    for (const property of ['fontSize', 'lineHeight', 'letterSpacing']) {
      add(common, `${prefix}.${property}`, token.value[property], token.usage);
    }
    for (const weight of ['regular', 'medium', 'bold']) {
      const value = token.value.fontWeight[weight];
      if (!Number.isFinite(value)) throw new Error(`Invalid font weight: ${variant}.${weight}`);
      add(common, `${prefix}.${weight}`, value);
    }
    const cssPrefix = `--${kebab(prefix)}`;
    classes.push(`.${className} {\n` +
      `  font-size: var(${cssPrefix}-font-size);\n` +
      `  line-height: var(${cssPrefix}-line-height);\n` +
      `  letter-spacing: var(${cssPrefix}-letter-spacing);\n` +
      `  font-weight: var(${cssPrefix}-regular);\n}`);
    for (const weight of ['regular', 'medium', 'bold']) {
      classes.push(`.${className}--${weight} {\n  font-weight: var(${cssPrefix}-${weight});\n}`);
    }
  }

  const root = new Map(common);
  for (const [name, token] of light) {
    if (root.has(name)) throw new Error(`Root variable collision: ${name}`);
    root.set(name, token);
  }

  const css = [
    '/* Generated by npm run tokens. Do not edit this file directly.\n' +
    ' * Source: design/montage.tokens.json\n' +
    ' * Original units and resolved alpha values are preserved.\n' +
    ' * Set data-theme="dark" on <html> to use the dark theme.\n' +
    ' */',
    renderBlock(':root', root),
    renderBlock('[data-theme="dark"]', dark),
    '/* Typography: use the base class and an optional weight modifier. */',
    ...classes,
    '',
  ].join('\n\n');

  await mkdir(new URL('../src/', import.meta.url), { recursive: true });
  await writeFile(outputUrl, css, 'utf8');
  console.log(`Generated src/tokens.css: ${root.size} root variables, ${dark.size} dark overrides, ${classNames.size} typography styles.`);
}

main().catch((error) => {
  console.error(`Token build failed: ${error.message}`);
  process.exitCode = 1;
});
